version: '3.9'

services:
  postgres_db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  flask_app:
    build: .
    container_name: flask_app
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://user:secret@postgres_db:5432/postgres
      FLASK_APP: flaskintro:create_app
      FLASK_CONFIG: DevelopmentConfig
    ports:
      - "5000:5000"
    command: flask run --host=0.0.0.0

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - postgres_db
    ports:
      - "8080:8080"

volumes:
  postgres_data:


networks:
  default:
    name: flasknet
